version: '3.8'
services:
  bot:
    image: ${REGISTRY_IMAGE:-random-winner-bot:latest}
    build: .
    container_name: random-winner-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'


